https://so1o.xyz/feed.xml
https://www.brycewray.com/index.xml
https://bluelander.dreamwidth.org/data/rss
https://wilw.dev/rss.xml
https://peterbabic.dev/atom.xml
https://blog.grayw.co.uk/rss/
https://zerokspot.com/index.xml
https://hamatti.org/feed/feed.xml
https://www.paritybit.ca/feed.xml
https://fullcirclemagazine.org/index.xml
https://drewdevault.com/blog/index.xml
https://cblgh.org/all.xml
https://adol.pw/index.xml
https://alexschroeder.ch/view/index.rss
https://snikket.org/blog/index.xml
https://www.spacebar.news/rss/
https://0pointer.net/blog/index.rss20
https://status.sr.ht/index.xml
https://blog.elementary.io/feed.xml
https://blog.bshah.in/feed.xml
https://steady.substack.com/feed
https://hackerstations.com/index.xml
https://thesam.zone/tags/beryl/index.xml
https://blog.lukaszolejnik.com/rss/
https://dev.37signals.com/feed/posts.xml
https://fuckiwishiknewth.at/feed/
https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/rss.xml
https://rss.beehiiv.com/feeds/gQxaV1KHkQ.xml
https://kentcdodds.com/blog/rss.xml
https://shiftmag.dev/feed/
https://www.ordemdospsicologos.pt/pt/feed/news
https://www.ces.uc.pt/rss/eventos.xml
https://www.ces.uc.pt/rss/oportunidades.xml
https://www.exploit-db.com/rss.xml
https://www.kali.org/rss.xml
https://www.noticiasaominuto.com/rss/ultima-hora
https://www.noticiasaominuto.com/rss/pais
https://www.noticiasaominuto.com/rss/mundo
https://indymedia.pt/feed/
https://www.youtube.com/feeds/videos.xml?channel_id=UCKxb1p0OzXuiAQBkiY0dCGg
https://www.youtube.com/feeds/videos.xml?channel_id=UCekHC2vD2SZ48pEi0SKGbqA
https://proton.me/blog/feed
https://www.baeldung.com/cs/feed
https://feeds.feedblitz.com/baeldung/linux&x=1
https://www.reddit.com/r/worldnews/.rss
https://fosstorrents.com/feed/torrents.xml
https://devblogs.microsoft.com/typescript/feed/
http://feeds.feedburner.com/daily-express-news-showbiz
https://www.baeldung.com/cs/feed
https://feeds.feedblitz.com/baeldung/linux&x=1
https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada
https://openculture.com/rss
https://www.technologyreview.com/topnews.rss
https://uxstudioteam.com/ux-blog/feed/
https://www.invisionapp.com/inside-design/feed
https://www.gsmarena.com/rss-news-reviews.php3
https://edm.com/.rss/full/
http://songexploder.net/feed
https://alistapart.com/main/feed/
https://www.youtube.com/feeds/videos.xml?user=LinusTechTips
https://startupjunkie.libsyn.com/rss
https://feeds.simplecast.com/dLRotFGk
https://reddit.com/r/movies/.rss
https://www.thehistoryreader.com/feed/
https://www.scmp.com/rss/91/feed
https://medium.com/feed/better-programming
https://codeascraft.com/feed/atom/
https://feeds.feedburner.com/codinghorror
https://programming.dev/feeds/c/gamedev.xml?sort=Active
https://rss.slashdot.org/Slashdot/slashdotMain
https://www.techrepublic.com/rssfeeds/topic/open-source/
https://css-tricks.com/feed/
https://davidwalsh.name/feed
https://www.smashingmagazine.com/feed
http://scripting.com/rss.xml
https://www.ikeahackers.net/feed
https://www.thecrazyprogrammer.com/category/programming/feed
https://github.blog/feed/
https://feeds.simplecast.com/XA_851k3
http://rss.sciam.com/sciam/60secsciencepodcast
http://feeds.bbci.co.uk/news/science_and_environment/rss.xml
https://feeds.npr.org/510308/podcast.xml
https://probablyscience.libsyn.com/rss
https://pa.tedcdn.com/feeds/talks.rss
https://hnrss.org/frontpage
http://feeds.feedburner.com/twistvid
https://news.ycombinator.com/rss
https://bookriot.com/feed/
https://reddit.com/r/books/.rss
http://feeds.feedburner.com/GdsSecurityBlog
http://www.arneswinnen.net/feed/
https://blog.skullsecurity.org/feed
http://labofapenetrationtester.blogspot.com/feeds/posts/default
http://carnal0wnage.attackresearch.com/rss.xml
http://reverse.put.as/feed/
http://adsecurity.org/?feed=rss2
http://foxglovesecurity.com/feed/
http://www.acunetix.com/blog/feed/
http://malwaremustdie.blogspot.com/feeds/posts/default
http://feeds.feedburner.com/IrongeeksSecuritySite
http://w00tsec.blogspot.com/feeds/posts/default
http://www.blackhillsinfosec.com/?feed=rss2
http://blog.didierstevens.com/feed/
http://sakurity.com/blog/feed.xml
http://randywestergren.com/feed/
http://sethsec.blogspot.com/feeds/posts/default
http://derflounder.wordpress.com/feed/
http://www.unix-ninja.com/feed/rss/
https://trustfoundry.net/feed/
http://feeds.feedburner.com/SucuriSecurity
http://enigma0x3.wordpress.com/feed/
https://blog.g0tmi1k.com/atom.xml
https://www.wired.com/category/security/feed/
http://feeds.feedburner.com/CyberArms
https://www.grepular.com/rss
http://feeds.feedburner.com/PentestTools
http://thinkingmaliciously.blogspot.com/feeds/posts/default
https://www.trustedsec.com/feed/
http://g-laurent.blogspot.com/feeds/posts/default
https://objective-see.com/rss.xml
http://krebsonsecurity.com/feed/
http://www.darkoperator.com/blog/rss.xml
http://www.cert.org/blogs/rss.xml
http://silentbreaksecurity.com/feed/
https://fin1te.net/feed.xml
http://googleonlinesecurity.blogspot.com/atom.xml
http://erratasec.blogspot.com/feeds/posts/default
https://www.youtube.com/feeds/videos.xml?playlist_id=UU9Qa_gXarSmObPX3ooIQZrg 
https://www.reddit.com/r/netsec/.rss
http://feeds.feedburner.com/osboxes
https://krebsonsecurity.com/feed/
https://www.classificadosx.net/pt/blog/feed/rss/blog?format=feed
https://social.growyourown.services/@homegrown.rss
https://forgejo.org/rss.xml
http://www.nodo50.org/rdf/nodo50.rss
https://www.systemli.org//en/index.xml
https://www.exploit-db.com/rss.xml
https://exposingtheinvisible.org/rss.xml
https://www.anarsec.guide/atom.xml
https://feeds.feedburner.com/Net-empregos
