#!/bin/bash 
# Clone several repos from Github about Security 
# OscarFM 2024

GC="git clone --recurse-submodules "

${GC} https://github.com/trimstray/the-book-of-secret-knowledge
${GC} https://github.com/Hack-with-Github/Awesome-Hacking
${GC} https://github.com/swisskyrepo/PayloadsAllTheThings
${GC} https://github.com/gatsbyjs/gatsby
${GC} https://github.com/caddyserver/caddy
${GC} https://github.com/danielmiessler/SecLists
${GC} https://github.com/x64dbg/x64dbg
${GC} https://github.com/eugenp/tutorials
${GC} https://github.com/mitmproxy/mitmproxy
${GC} https://github.com/QuivrHQ/quivr
${GC} https://github.com/trailofbits/algo
${GC} https://github.com/OWASP/CheatSheetSeries
${GC} https://github.com/StevenBlack/hosts
${GC} https://github.com/shieldfy/API-Security-Checklist
${GC} https://github.com/aquasecurity/trivy
${GC} https://github.com/FallibleInc/security-guide-for-developers
${GC} https://github.com/drduh/macOS-Security-and-Privacy-Guide
${GC} https://github.com/radareorg/radare2
${GC} https://github.com/authelia/authelia
${GC} https://github.com/matomo-org/matomo
${GC} https://github.com/gentilkiwi/mimikatz
${GC} https://github.com/Lissy93/web-check
${GC} https://github.com/cilium/cilium
${GC} https://github.com/InterviewMap/CS-Interview-Knowledge-Map
${GC} https://github.com/slimtoolkit/slim
${GC} https://github.com/projectdiscovery/nuclei
${GC} https://github.com/imthenachoman/How-To-Secure-A-Linux-Server
${GC} https://github.com/The-Art-of-Hacking/h4cker
${GC} https://github.com/gravitational/teleport
${GC} https://github.com/MobSF/Mobile-Security-Framework-MobSF
${GC} https://github.com/bettercap/bettercap
${GC} https://github.com/Lissy93/personal-security-checklist
${GC} https://github.com/gitleaks/gitleaks
${GC} https://github.com/ory/hydra
${GC} https://github.com/getsops/sops
${GC} https://github.com/rizinorg/cutter
${GC} https://github.com/trufflesecurity/trufflehog
${GC} https://github.com/slackhq/nebula
${GC} https://github.com/Hacker0x01/hacker101
${GC} https://github.com/tink-crypto/tink
${GC} https://github.com/GyulyVGC/sniffnet
${GC} https://github.com/zaproxy/zaproxy
${GC} https://github.com/threat9/routersploit
${GC} https://github.com/Infisical/infisical
${GC} https://github.com/twpayne/chezmoi
${GC} https://github.com/sbilly/awesome-security
${GC} https://github.com/OWASP/owasp-mastg
${GC} https://github.com/maurosoria/dirsearch
${GC} https://github.com/Atlas-OS/Atlas
${GC} https://github.com/jopohl/urh
${GC} https://github.com/veeral-patel/how-to-secure-anything
${GC} https://github.com/secdev/scapy
${GC} https://github.com/helmetjs/helmet
${GC} https://github.com/GTFOBins/GTFOBins.github.io
${GC} https://github.com/google/oss-fuzz
${GC} https://github.com/mvt-project/mvt
${GC} https://github.com/trimstray/the-practical-linux-hardening-guide
${GC} https://github.com/digininja/DVWA
${GC} https://github.com/prowler-cloud/prowler
${GC} https://github.com/juice-shop/juice-shop
${GC} https://github.com/nmap/nmap
${GC} https://github.com/apsdehal/awesome-ctf
${GC} https://github.com/arkenfox/user.js
${GC} https://github.com/wazuh/wazuh
${GC} https://github.com/upgundecha/howtheysre
${GC} https://github.com/gravitl/netmaker
${GC} https://github.com/docker/docker-bench-security 
${GC} https://github.com/toniblyx/my-arsenal-of-aws-security-tools
${GC} https://github.com/monero-project/monero
${GC} https://github.com/infosecn1nja/Red-Teaming-Toolkit
${GC} https://github.com/spring-projects/spring-security
${GC} https://github.com/samratashok/nishang
${GC} https://github.com/wpscanteam/wpscan
${GC} https://github.com/bregman-arie/devops-resources
${GC} https://github.com/zardus/ctf-tools
${GC} https://github.com/juliocesarfort/public-pentesting-reports
${GC} https://github.com/We5ter/Scanners-Box
${GC} https://github.com/projectdiscovery/nuclei-templates
${GC} https://github.com/jofpin/trape
${GC} https://github.com/shadowsocks/shadowsocks-rust
${GC} https://github.com/crowdsecurity/crowdsec
${GC} https://github.com/ashishb/android-security-awesome
${GC} https://github.com/linkedin/school-of-sre
${GC} https://github.com/anchore/grype
${GC} https://github.com/owasp-modsecurity/ModSecurity
${GC} https://github.com/1N3/Sn1per
${GC} https://github.com/securego/gosec
${GC} https://github.com/go-acme/lego
${GC} https://github.com/hslatman/awesome-threat-intelligence
${GC} https://github.com/unicorn-engine/unicorn
${GC} https://github.com/meirwah/awesome-incident-response
${GC} https://github.com/capstone-engine/capstone
${GC} https://github.com/falcosecurity/falco
${GC} https://github.com/maxgoedjen/secretive
${GC} https://github.com/jivoi/awesome-ml-for-cybersecurity
${GC} https://github.com/OWASP/wstg
${GC} https://github.com/edoardottt/awesome-hacker-search-engines
${GC} https://github.com/frappe/frappe
${GC} https://github.com/goauthentik/authentik
${GC} https://github.com/paragonie/awesome-appsec
${GC} https://github.com/onionshare/onionshare
${GC} https://github.com/trickest/cve 
${GC} https://github.com/pterodactyl/panel 
${GC} https://github.com/yaklang/yakit
${GC} https://github.com/v1s1t0r1sh3r3/airgeddon
${GC} https://github.com/PyCQA/bandit
${GC} https://github.com/sqlcipher/sqlcipher
${GC} https://github.com/nomi-sec/PoC-in-GitHub
${GC} https://github.com/0xInfection/Awesome-WAF
${GC} https://github.com/zeek/zeek
${GC} https://github.com/ntop/ntopng
${GC} https://github.com/Lissy93/awesome-privacy
${GC} https://github.com/jeremylong/DependencyCheck
${GC} https://github.com/duo-labs/cloudmapper
${GC} https://github.com/telekom-security/tpotce
${GC} https://github.com/PrivateBin/PrivateBin
${GC} https://github.com/Ignitetechnologies/Mindmap
${GC} https://github.com/stamparm/maltrail
${GC} https://github.com/tutao/tutanota
${GC} https://github.com/projectcalico/calico
${GC} https://github.com/LasCC/HackTools
${GC} https://github.com/infoslack/awesome-web-hacking
${GC} https://github.com/ViRb3/wgcf
${GC} https://github.com/rmusser01/Infosec_Reference
${GC} https://github.com/daffainfo/AllAboutBugBounty
${GC} https://github.com/xairy/linux-kernel-exploitation
${GC} https://github.com/CTFd/CTFd
${GC} https://github.com/farhanashrafdev/90DaysOfCyberSecurity
${GC} https://github.com/yeahhub/Hacking-Security-Ebooks
${GC} https://github.com/j3ssie/osmedeus
${GC} https://github.com/jakejarvis/awesome-shodan-queries
${GC} https://github.com/majd/ipatool
${GC} https://github.com/onlurking/awesome-infosec
${GC} https://github.com/NullArray/AutoSploit
${GC} https://github.com/decalage2/awesome-security-hardening
${GC} https://github.com/snyk/cli
${GC} https://github.com/deepfence/ThreatMapper
${GC} https://github.com/OlivierLaflamme/Cheatsheet-God
${GC} https://github.com/aircrack-ng/aircrack-ng
${GC} https://github.com/forter/security-101-for-saas-startups
${GC} https://github.com/slowmist/Blockchain-dark-forest-selfguard-handbook
${GC} https://github.com/OpenCTI-Platform/opencti
${GC} https://github.com/rapid7/metasploitable3
${GC} https://github.com/DominicBreuker/pspy
${GC} https://github.com/andresriancho/w3af
${GC} https://github.com/authzed/spicedb
${GC} https://github.com/tenable/terrascan
${GC} https://github.com/Trusted-AI/adversarial-robustness-toolbox
${GC} https://github.com/build-trust/ockam
${GC} https://github.com/ossec/ossec-hids
${GC} https://github.com/jassics/security-study-plan
${GC} https://github.com/LyleMi/Learn-Web-Hacking
${GC} https://github.com/ossf/scorecard
${GC} https://github.com/OISF/suricata
${GC} https://github.com/RhinoSecurityLabs/pacu
${GC} https://github.com/orhanobut/hawk
${GC} https://github.com/fabacab/awesome-cybersecurity-blueteam
${GC} https://github.com/PaulSec/awesome-sec-talks
${GC} https://github.com/rudderlabs/rudder-server
${GC} https://github.com/toolswatch/blackhat-arsenal-tools
${GC} https://github.com/Consensys/mythril
${GC} https://github.com/Arachni/arachni
${GC} https://github.com/trailofbits/manticore
${GC} https://github.com/hahwul/WebHackersWeapons
${GC} https://github.com/urbanadventurer/Android-PIN-Bruteforce
${GC} https://github.com/webhintio/hint
${GC} https://github.com/briansmith/ring
${GC} https://github.com/cloud-hypervisor/cloud-hypervisor
${GC} https://github.com/WithSecureLabs/drozer
${GC} https://github.com/r0ysue/AndroidSecurityStudy
${GC} https://github.com/meshbird/meshbird
${GC} https://github.com/lc/gau
${GC} https://github.com/knownsec/pocsuite3
${GC} https://github.com/smallstep/cli
${GC} https://github.com/GhostPack/Seatbelt
${GC} https://github.com/undergroundwires/privacy.sexy
${GC} https://github.com/open-policy-agent/gatekeeper
${GC} https://github.com/builtbybel/privatezilla
${GC} https://github.com/bunkerity/bunkerweb
${GC} https://github.com/yokoffing/Betterfox
${GC} https://github.com/DefectDojo/django-DefectDojo
${GC} https://github.com/2factorauth/twofactorauth
${GC} https://github.com/nixawk/pentest-wiki 
${GC} https://github.com/0x4D31/awesome-threat-detection
${GC} https://github.com/scipag/vulscan
${GC} https://github.com/ivre/ivre
${GC} https://github.com/lwthiker/curl-impersonate
${GC} https://github.com/zhzyker/vulmap
${GC} https://github.com/noraj/OSCP-Exam-Report-Template-Markdown
${GC} https://github.com/cilium/hubble
${GC} https://github.com/hahwul/dalfox
${GC} https://github.com/chanakaudaya/solution-architecture-patterns
${GC} https://github.com/cilium/tetragon
${GC} https://github.com/aquasecurity/tracee
${GC} https://github.com/TheHive-Project/TheHive
${GC} https://github.com/paragonie/paseto
${GC} https://github.com/S3cur3Th1sSh1t/WinPwn 
${GC} https://github.com/reddelexc/hackerone-reports
${GC} https://github.com/aquasecurity/cloudsploit
${GC} https://github.com/linkedin/qark
${GC} https://github.com/nabla-c0d3/sslyze
${GC} https://github.com/jtesta/ssh-audit
${GC} https://github.com/PurpleI2P/i2pd
${GC} https://github.com/buzzfeed/sso
${GC} https://github.com/projectdiscovery/interactsh
${GC} https://github.com/skerkour/black-hat-rust
${GC} https://github.com/gwen001/pentest-tools
${GC} https://github.com/microsoft/Security-101
${GC} https://github.com/google/honggfuzz
${GC} https://github.com/microcosm-cc/bluemonday
${GC} https://github.com/ExpressGateway/express-gateway
${GC} https://github.com/deepfence/SecretScanner
${GC} https://github.com/OWASP/Nettacker
${GC} https://github.com/google/security-research
${GC} https://github.com/jaredthecoder/awesome-vehicle-security
${GC} https://github.com/airbnb/streamalert
${GC} https://github.com/chipsec/chipsec
${GC} https://github.com/sozu-proxy/sozu
${GC} https://github.com/inspec/inspec
${GC} https://github.com/vaib25vicky/awesome-mobile-security
${GC} https://github.com/hardentools/hardentools
${GC} https://github.com/jekil/awesome-hacking
${GC} https://github.com/milesmcc/shynet
${GC} https://github.com/Security-Onion-Solutions/securityonion
${GC} https://github.com/decalage2/oletools
${GC} https://github.com/Netflix/bless
${GC} https://github.com/zan8in/afrog
${GC} https://github.com/google/nsjail
${GC} https://github.com/pyllyukko/user.js
${GC} https://github.com/QData/TextAttack
${GC} https://github.com/arainho/awesome-api-security
${GC} https://github.com/baidu/openrasp
${GC} https://github.com/JPCERTCC/LogonTracer
${GC} https://github.com/aya-rs/aya
${GC} https://github.com/payloadbox/command-injection-payload-list
${GC} https://github.com/DedSecInside/TorBot
${GC} https://github.com/the-tcpdump-group/tcpdump
${GC} https://github.com/WithSecureLabs/chainsaw
${GC} https://github.com/OWASP/ASVS
${GC} https://github.com/awnumar/memguard
${GC} https://github.com/activecm/rita
${GC} https://github.com/EnergizedProtection/block
${GC} https://github.com/nanovms/nanos
${GC} https://github.com/cerbos/cerbos
${GC} https://github.com/V33RU/IoTSecurity101
${GC} https://github.com/symfony/security-bundle
${GC} https://github.com/flipkart-incubator/Astra
${GC} https://github.com/Permify/permify
${GC} https://github.com/RhinoSecurityLabs/cloudgoat
${GC} https://github.com/jedisct1/piknik
${GC} https://github.com/mgeeky/Penetration-Testing-Tools
${GC} https://github.com/OpenSC/OpenSC
${GC} https://github.com/ph4ntonn/Stowaway
${GC} https://github.com/0xsyr0/OSCP
${GC} https://github.com/e-m-b-a/emba
${GC} https://github.com/r0oth3x49/ghauri
${GC} https://github.com/DependencyTrack/dependency-track
${GC} https://github.com/outflanknl/RedELK
${GC} https://github.com/esc0rtd3w/wifi-hacker
${GC} https://github.com/gmh5225/awesome-game-security 
