#!/bin/bash
# cargo Applications to install 
# All of them run inside a terminal
# Most have use a TUI ( Terminal User Interface ) 

cargo install bat
cargo install gitui
cargo install kmon
cargo install iamb
cargo install so
cargo install tui-journal
cargo install wiki-tui
cargo install bandwhich




